default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: usuario_dev
  username: leon
  password: leon
test:
  <<: *default
  database: usuario_test
  username: leon
  password: leon

production:
  <<: *default
  database: vendedores_production
  username: vendedores
  password: <%= ENV["VENDEDORES_DATABASE_PASSWORD"] %>
